---
Name: socialshare
---
Page:
  extensions:
    - Innoweb\SocialShare\Extensions\PageExtension
PageController:
  extensions:
    - Innoweb\SocialShare\Extensions\PageControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialShare\Extensions\ConfigExtension
Innoweb\SocialShare\Extensions\ConfigExtension:
  multisites_enable_global_settings: false
  enable_base_share: false
---
Only:
  classexists: 'Symbiote\Multisites\Multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialShare\Extensions\ConfigExtension
