---
Name: socialshare
---
Page:
  extensions:
    - Innoweb\SocialShare\Extensions\PageExtension
PageController:
  extensions:
    - Innoweb\SocialShare\Extensions\PageControllerExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialShare\Extensions\ConfigExtension
Innoweb\SocialShare\Extensions\ConfigExtension:
  multisites_enable_global_settings: false
  enable_base_share: false

---
Only:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialShare\Extensions\ConfigExtension

---
Only:
  moduleexists:
    - 'fromholdio/silverstripe-configured-multisites'
---
Fromholdio\ConfiguredMultisites\Model\Site:
  extensions:
    - Innoweb\SocialShare\Extensions\ConfigExtension
